### ISSUE TITLE
Set up a new Netapp volume on the confidential SVM that is only accessible from exec servers,

### ISSUE THREAD

**Issue by mreekie** [hmdc/PM-nocode#47]
Set up a new Netapp volume on the confidential SVM that is only accessible from exec servers, rcesrv-vm2, and scan6-1. Do all the usual setup steps for volumes, including adding it to clamav scans. (Volume should be read-write to also hold output data although data security plan originally said volume would be read-only.)

**Comment by iqlinuxadmin** [comment]
Done!
